# Description of the docker environment for testing spark jobs
#
# Instances a very small cluster with a master node and a worker node
#
version: '2'

services:

  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./configs/config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      HADOOP_HOME: "/opt/hadoop"
    volumes:
      - namenodedata:/tmp

  datanode:
    image: apache/hadoop:3
    command: ["hdfs", "datanode"]
    env_file:
      - ./configs/config
    volumes:
      - datanodedata:/tmp

  resourcemanager:
    image: apache/hadoop:3
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./configs/config

  nodemanager:
    image: apache/hadoop:3
    command: [ "yarn", "nodemanager" ]
    ports:
      - 8042:8042
    env_file:
      - ./configs/config

  # HIVE server to more easily query the data from hadoop
  hive_server:
    image: apache/hive:3.1.3
    ports:
      - 10000:10000
      - 10002:10002
    environment:
      - SERVICE_NAME=hiveserver2
      - HIVE_CUSTOM_CONF_DIR=/hive_conf
    volumes:
      - ./configs:/hive_conf
      - hiveserverdata:/opt/hive/data/warehouse

  # Front-end to be able to query hive more easily
  hue_server:
    image: gethue/hue:latest
    ports:
      - 8888:8888
    volumes:
      - ./configs/hue/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - "database"

  # MYSQL Database to support hue
  database:
    image: mysql:5.7
    ports:
      - 33061:3306
    command: --init-file /data/application/init.sql
    volumes:
      - mysqldata:/var/lib/mysql
      - ./configs/mysql/init.sql:/data/application/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: hue
        MYSQL_USER: adm
        MYSQL_PASSWORD: secret

  # Spark client
  spark:
    build: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - YARN_CONF_DIR=/opt/bitnami/spark/custom_configs
    ports:
      - '8080:8080'
    volumes:
      - ./config/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./configs:/opt/bitnami/spark/custom_configs
      - .:/opt/bitnami/spark/scripts

volumes:
  mysqldata:
  hiveserverdata:
  namenodedata:
  datanodedata:
